# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e7b7f35add9e9a9b98bea9fbbd0b456fe146b2964d519c319e8facf5fac330035acd80e728d0f74978b0dde9e8f8b850d24d55ab4ea89645dd6f33b8f838cc

test:
  secret_key_base: 1f27cbb59944518bf8c0974ec995c04dc15eee5f0663bd8b5f7ed7ca04146667f5ef0c72c1793bfcd0269ea64b6e612a22b6c33703e085c78bba507ecd9fc882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
